[workspace]
members = [
    "latex2mmlc",
    # "latex2mmlc_cli",
    "latex2mmlc_python",
]
resolver = "2"

[workspace.package]
edition = "2021"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
